services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data:rw
    networks:
      - network
    env_file:
      - ./configs/database/.env
    restart: unless-stopped

  cache:
    image: redis:alpine
    networks:
      - network
    restart: unless-stopped
  
  directus:
    image: directus/directus:10.11.0
    volumes:
      - ./uploads:/directus/uploads:rw
      - ./extensions:/directus/extensions:rw
      - ./snapshots:/directus/snapshots:rw
    depends_on:
      - cache
      - database
    networks:
      - network
    env_file:
      - ./configs/directus/.env
    restart: unless-stopped

networks:
  network:
    external: true
    name: evola