services:
  database:
    image: postgis/postgis:17-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data:rw
    networks:
      - network
    env_file:
      - ./configs/database/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  cache:
    image: redis:alpine
    networks:
      - network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
  
  directus:
    image: directus/directus:11.9.2
    volumes:
      - ./uploads:/directus/uploads:rw
      - ./extensions:/directus/extensions:rw
      - ./snapshots:/directus/snapshots:rw
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - network
    env_file:
      - ./configs/directus/.env
    restart: unless-stopped

networks:
  network:
    external: true
    name: evola