services:
  evola-api:
    image: dmportella/evola-mail:${HASH}
    container_name: evola-mail
    restart: unless-stopped
    env_file:
      - web-variables.env
    networks:
      - evola-api_default
    volumes:
      - ./data:/usr/app/src/data:rw

networks: 
  evola-api_default:
    name: evola-api_default
    external: true
