services:
  evola-api:
    image: dmportella/evola-mail:latest
    container_name: evola-mail
    restart: unless-stopped
    env_file:
      - web-variables.env
    networks:
      - network
    volumes:
      - ./data:/usr/app/src/data:rw

networks: 
  network:
    name: evola_network
    external: true
