services:
  evola-api:
    image: dmportella/evola-api:latest
    container_name: evola-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1880:1880"
    networks:
      - network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: evola-api-nginx
    ports:
      - "80:80"
      - "443:443"
      - "8055:8055"
    volumes:
      - ./data/nginx:/etc/nginx
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    networks:
      - network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: evola-api-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
      - ./data/certbot/logs:/var/log/letsencrypt:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
networks:
  network:
    external: true
    name: evola
