services:
  evola-api:
    image: dmportella/evola-api:${HASH}
    container_name: evola-api
    restart: unless-stopped
    env_file:
      - web-variables.env
    ports:
      - "1880:1880"
    networks:
      - evola-api_default

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: evola-api-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    networks:
      - evola-api_default
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    container_name: evola-api-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks: 
  evola-api_default:
    name: evola-api_default
    external: true
